---
title: "IMFTaxMap"
output: md_document
---

#- Mapping IMF Conditionality Agreements on Revenues and Tax issues

# Data source: IMFMonitor.org (see also Kentikelenis, A., Stubbs, T., & King, L. (2016). IMF conditionality and development policy space, 1985–2014. Review of International Political Economy, 23(4), 543–582.)

# Code inspiration: Eric C. Anderson (http://eriqande.github.io/rep-res-web/lectures/making-maps-with-R.html)

# Loading libraries

library(ggplot2)
library(ggmap)
library(maps)
library(mapdata)
library(RColorBrewer)

# Reading the IMF data

imftaxmap <- read.csv("imftaxmap.csv",sep=";")

# Defining the world map

world <- map_data("world")

# Showing a simple world map

ggplot() + geom_polygon(data=world,aes(x=long,y=lat,group=group),color="black",fill=NA) + geom_polygon(color="black",fill="NA") + coord_fixed(1.3)

# Merging the IMF data and the maps world coordinates

imftax <- inner_join(world,imftaxmap,by="region")

# Mapping the data

imf_base <- ggplot(data=world,mapping=aes(x=long,y=lat,group=group)) + coord_fixed(1.3) + geom_polygon(color="black",fill="white")

# Preparing to clean the plot, removing axes and ticks

ditch_the_axes <- theme(axis.text = element_blank(),axis.line = element_blank(),axis.ticks = element_blank(),panel.border = element_blank(),panel.grid = element_blank(), axis.title = element_blank())

# Showing the cleaned plot with agreement counts

elbow_room1 <- imf_base + geom_polygon(data = imftax, aes(fill = count), color = "white") + geom_polygon(color = "black", fill = NA) + theme_bw() + ditch_the_axes

elbow_room1

# Defining a better gradient colour scale

iPalette <- brewer.pal(9,"YlOrRd")

# Final plot (our cleaned plot + the new colour scale + labels + aligned caption)

elbow_room1 + scale_fill_gradientn(colours=iPalette,guide="colourbar",name="Number of Agreements",breaks=c(0,20,40,60,80,100,120,140)) + labs(title="IMF Conditionality Agreements on Revenues and Tax issues", subtitle="All applicable IMF agreements, 1978-2014 (n=3349, nCountries=113)", caption="Data: IMFMonitor.org | Plot: Rasmus Christensen phdskat.org @phdskat") + theme(plot.caption=element_text(hjust=1.2))

# Saving the plot

ggsave("imftaxmap.png",width=18,height=9.33,dpi=500)

# saving this file

library(rmarkdown)
render("IMFTaxMap.Rmd",output_format="word_document")